PMEAL/OpenPNM

OpenPNM/Geometry/__GenericGeometry__.py, OpenPNM/Physics/__GenericPhysics__.py
Seems to work, physics now pull in data from phases, and geoms now pull ......in data from networks
=> bidirectional getitem

OpenPNM/Algorithms/__GenericAlgorithm__.py, OpenPNM/Algorithms/__GenericLinearTransport__.py, OpenPNM/Network/__GenericNetwork__.py, OpenPNM/Utilities/__topology__.py
GenericLinearTransport and GenericAlgorithm have been modified to be consistent with the other sections of the code. 
The only problem for them based on pep8, will be the length of the lines.
=> Algorithm clean up

OpenPNM/Physics/models/generic_source_term.py
This is the improved version of generic_source_term model for pep8. 
The functionality of the model has not been changed.
=> Modified generic_source_term.

.gitignore, OpenPNM/Base/__Core__.py
This branch should be merged after #361 
Addressing #358 
We'll reimplement the test in a following branch that'll be purposed with getting our test coverage up.
=> Fix bug 358

env.sh
Removing this artifact script from 2013.
@jgostick @putza
=> Remove env.sh

OpenPNM/Network/__GenericNetwork__.py
- This method puts a -1 in all pores and throats that are not invaded, which save the trouble of doing this manually each time the existing find_clusters is called
- This new version also optionally returns both pore and throat clusters.  The default is no, so this method 'could' replace the existing one if the -1's don't break things
- Added a ton of doc string and examples to this method too
=> Added "find_clusters2"

OpenPNM/Base/__Controller__.py, OpenPNM/Base/__Core__.py, OpenPNM/Base/__ModelsDict__.py, OpenPNM/Base/__Tools__.py, bin/test, docs/_extensions/docscrape.py, test/unit/Base/ControllerTest.py, test/unit/Base/ModelsDictTest.py, test/unit/Base/ToolsTest.py
During my PEP8ification of OpenPNM I broke a few string methods. This PR should that as well as doing an extra check when initializing a `ModelWraper`.
@maghighi @jgostick
=> Fix __str__ methods

OpenPNM/Algorithms/__GenericAlgorithm__.py, OpenPNM/Algorithms/__GenericLinearTransport__.py, pytest.ini
This PR includes some modifications regarding pep8 rules.  No new functionality has been added to the the two long files (GenericAlgorithm and GenericLinearTransport). They are only modified for pep8,
=> Improved solver

OpenPNM/Base/__Controller__.py
There was a typo in the str method of the controller. It was causing
some problems for printing the controller especially if there was any
mixture phase in the simulation.
=> Fixed minor bug in the controller

.travis.yml, bin/test, pytest.ini
A small PR to ensure that we only need to maintain a single test command.
@jgostick
=> Fixed the test script

.travis.yml, README.rst, test_requirements.txt
Our coveralls experiment has proved to been a bit troublesome. Codecov has gotten a lot of good press lately and has a very responsive team of developers, so I believe they are worth trying out.
This PR should be merged after #400
=> Replacing coveralls

OpenPNM/Algorithms/__GenericAlgorithm__.py, OpenPNM/Algorithms/__GenericLinearTransport__.py, OpenPNM/Physics/models/generic_source_term.py, test/integration/script_test.py, test/unit/Algorithms/GenericAlgorithmTest.py, test/unit/Algorithms/GenericLinearTransportTest.py, test/unit/Physics/models/GenericSourceTerm.py
I noticed that I have some unit tests in one of my private branches. I don't think they will change the overall coverage significantly, but at least they test different modes of solver/source_term thoroughly.
=> Extra unit tests

OpenPNM/Network/__Cubic__.py, OpenPNM/Utilities/__topology__.py, test/integration/test_topological_manipulations.py, test/unit/Network/CubicTest.py
The bug  #428 is fixed now. It was a minor bug due to the wrong naming inside the method. 
Also some topological methods and their unit tests have been added.
I had these changes in one of my private branches for a long time. There are still some changes for improving subdivide method which are important, (especially for multi-scale systems), but since I do not have the necessary tests for them at this moment, I'll make another pull request for them in near future.
=> Subdivide modification

OpenPNM/Utilities/__topology__.py, test/unit/Utilities/TopologyTest.py
This method was much easier to make than I thought, so I just went ahead and address #427.
=> Merge pores

docs/examples/percolation.rst
Fixed the site and bond percolation example
=> Perc example

.travis.yml, OpenPNM/__init__.py
This should prevent new users from banging their heads when getting started.
=> Added a Python version check to the package init.  

OpenPNM/Network/__GenericNetwork__.py, OpenPNM/Utilities/misc.py, test/unit/Network/GenericNetworkTest.py, test/unit/Utilities/UtilitiesMiscTest.py
This PR adds a method for finding the throat or throats that connects given pairs of pores
=> Find connecting throats

OpenPNM/Network/__GenericNetwork__.py, test/unit/Network/GenericNetworkTest.py
The network health check now looks for two more problems: looped throats, and headless throats.
=> Improve health check

OpenPNM/Network/__Cubic__.py
Changed the default behavior of add_boundary_pore when apply_label is not given...forgot to change this before merging.
=> Minor fix to add_boundary_pores

OpenPNM/Base/__Core__.py
This PR adds the ability to allow for None inputs which will now result in an empty array being returned.
=> minor addition to _parse_locations

OpenPNM/Base/__Core__.py, OpenPNM/Base/__Tools__.py, OpenPNM/Geometry/__GenericGeometry__.py, OpenPNM/Network/__GenericNetwork__.py, OpenPNM/Physics/__GenericPhysics__.py, pytest.ini, test/integration/test_network_methods.py, test/unit/Base/CoreTest.py, test/unit/Network/GenericNetworkTest.py, test_requirements.txt
This is a large refactoring of Core.  The main changes are/will be:
1. Created input parser private methods (for locations, element, modes)
2. Will probably split Core into something like FullDomain and PartialDomain
3. Lots of changes to the doc strings
=> Core cleanup

OpenPNM/Algorithms/__Drainage__.py, OpenPNM/Algorithms/__GenericLinearTransport__.py, OpenPNM/Algorithms/__init__.py, OpenPNM/Base/__Core__.py, OpenPNM/Geometry/__Voronoi__.py, OpenPNM/Physics/models/multiphase.py, OpenPNM/Utilities/vertexops.py, test/integration/test_drainage_algorithm.py, test/integration/test_percolation_algorithms.py, test/unit/Algorithms/DrainageTest.py, test/unit/Geometry/VoronoiTest.py, test/unit/Physics/models/MultiPhaseTest.py
This is the beginning of a set of changes proposed to the drainage algorithms as pointed out in issue #459.  
Eventually, this PR will create a more simplified drainage algorithm (including trapping and residual phase), and also an imbibition algorithm that uses pore sizes instead of throat sizes.
=> Drainage algs

OpenPNM/Algorithms/__Drainage__.py, OpenPNM/Algorithms/__OrdinaryPercolation__.py, OpenPNM/Geometry/models/throat_length.py, OpenPNM/Physics/models/multiphase.py, test/integration/test_drainage_algorithm.py, test/unit/Algorithms/DrainageTest.py
This pull request addresses issue #486
=> Drainage tweak

OpenPNM/Algorithms/__Drainage__.py, OpenPNM/Algorithms/__GenericLinearTransport__.py, OpenPNM/Base/__ModelsDict__.py
@mohammadamin-sadeghi has been working on issue #479, specifically renaming 'regenerate' to 'run' to be more clear.
=> Changed "regenerate" to "run".

test/unit/Base/ModelsDictTest.py
This is to address issue #449.  The suspected bug does not exist, but I added a pile of tests anyway.
=> Enhanced testing modelsdict

OpenPNM/Network/__GenericNetwork__.py
This PR address issue #525.  I did not add any tests since this method just calls the ```find_neighbor_pores``` method which is already tested.
=> Add mode to num_neighbors

.travis.yml, OpenPNM/__init__.py, requirements.txt, setup.py
Changed setup.py to stop circular logic of importing package before i…nstalling it.  Changed how the version number is retrieved.
=> Fixing setup.py

OpenPNM/Base/__Controller__.py, OpenPNM/Base/__Core__.py, test/unit/Base/ControllerTest.py
=> Fix load simulation

.travis.yml, bin/test, pytest.ini, test_requirements.txt
I will be doing a lot of trial and error to see why codecov hasn't been working.
=> Trying to get codecov working again.

OpenPNM/Base/__Controller__.py, OpenPNM/Phases/__GenericPhase__.py, OpenPNM/Utilities/IO.py, OpenPNM/Utilities/misc.py, test/unit/Phases/GenericPhaseTest.py, test/unit/Utilities/IOTest.py, test/unit/Utilities/UtilitiesMiscTest.py
Removing several unused lines/blocks of code, and adding some unit tests
=> Remove cruft

OpenPNM/Algorithms/__GenericLinearTransport__.py, test/unit/Algorithms/GenericLinearTransportTest.py
This pull_request addresses the issue  #580. I have also added some more
unit tests to cover the issue.
=> fixed_boolean_mask_BC

OpenPNM/Network/__Cubic__.py
=> add_args_to_add_boundaries

OpenPNM/Geometry/models/pore_diameter.py, test/unit/Geometry/models/PoreDiameterTest.py
Totally awesome pore scale model to find the largest sphere you can put in each pore without over lapping any neighboring pores.
=> Largest sphere model

OpenPNM/Geometry/models/pore_seed.py
Changed from fitting a gaussian stats object to just using equations to renormalize the convoluted pore seeds
=> Minor tweak to pore_seed.spatially_correlated model

OpenPNM/Network/tools.py
Enhancing docstrings, adding minor functionality, and simplifying some functions
=> Enchancements to network tools

.travis.yml, README.rst
Changed travis.yml back to latest version of miniconda, updated the readme with comments about master branch stability
=> Admin changes

OpenPNM/Network/__DelaunayVoronoiDual__.py, test/unit/Network/DelaunayVoronoiDualTest.py
Removed 'boundary' label and converted them to 'surface'...to match the CubicDual class
=> Changing the labeling scheme on DelaunayVoronoiDual

OpenPNM/__init__.py, requirements.txt, setup.py
Added pyyaml to dependency in setup.py and specifed Python version 3.4+ in init and setup
=> Fixing issues #610 and #614 regarding dependencies

OpenPNM/Base/__Core__.py, test/unit/Base/CoreTest.py
Added the ability to handle 'pore.prop' as well as just 'pore' in _parse_element
=> Fix for issue #664

OpenPNM/Utilities/IO.py
Fixed potential bug where array was being overwritten on each loop. It now checks and only writes array if it doesn't already exist.  
( I have no idea why or how the old code worked.  It was sloppy coding on my part, but I obviously would have caught it had there been an error or problem. )
=> Fixed strange code in NetworkX import

.travis.yml, OpenPNM/Base/__ModelsDict__.py, OpenPNM/Network/tools.py, OpenPNM/Utilities/IO.py
There seems to be some errors thrown for using floats as indices
=> Fixing some new bugs that have cropped up in the Python 3.5 build

OpenPNM/Utilities/IO.py, test/unit/Utilities/IOTest.py
Adjusting the IO classes to return a Geometry along with the Network
=> Network import returns a Geometry

OpenPNM/Network/__GenericNetwork__.py
Optimizing OpenPNM to run faster.
=> Make OpenPNM Great Again!

OpenPNM/Algorithms/__Drainage__.py, OpenPNM/Algorithms/__GenericLinearTransport__.py, OpenPNM/Network/__Cubic__.py, OpenPNM/Physics/models/multiphase.py, OpenPNM/Utilities/IO.py
Rearranged some of the boolean masks in the linear transport algorithm to make the code compatible with the new version of Numpy.
=> Fixing Numpy boolean compatibility

docs/userguide/tutorials/advanced_tutorial.rst, docs/userguide/tutorials/getting_started.rst, example_script.py
Having gone through the tutorials, I am fixing errors and making small improvements to readability and explanations.
=> Tutorial improvements

example_script.py, openpnm/algorithms/Reaction.py, openpnm/core/Base.py, openpnm/core/ModelsMixin.py, openpnm/core/Simulation.py, openpnm/core/Workspace.py
This fixes several of the simple issues revealed during telecon on Feb 1st.
=> Address some open issues

openpnm/algorithms/GenericTransport.py
@jgostick  removed -ve sign of b in generic transport class as well.
=> removed -ve sign from apply_bc function in generictransport class as it was producing -ve results in alg1.results() in example_script

example_script.py, openpnm/algorithms/GenericTransport.py, openpnm/core/Base.py, openpnm/core/Project.py, openpnm/core/Subdomain.py, openpnm/core/__init__.py, openpnm/geometry/GenericGeometry.py, openpnm/network/Cubic.py, openpnm/network/GenericNetwork.py, openpnm/phases/GenericPhase.py, openpnm/physics/GenericPhysics.py, tests/unit/core/BaseTest.py, tests/unit/core/SubdomainTest.py, tests/unit/io/PandasTest.py
This is a backend change that I've been meaning to make for a while.  The GenericPhysics and GenericGeometry objects need an extra level of inheritance to reduce redundant code, pertaining to setting locations, and the getitem method.
=> Breakup base

openpnm/core/Project.py, tests/unit/core/ProjectTest.py
This PR is to flesh out the behavior of ``clear`` on all the objects
=> Enhancing clear methods

openpnm/network/Cubic.py, openpnm/network/CubicDual.py, openpnm/network/CubicTemplate.py, openpnm/utils/misc.py, tests/unit/network/CubicDualTest.py, tests/unit/network/CubicTemplateTest.py, tests/unit/utils/UtilsTest.py
cleaning up the utils module and adding tests
=> Test utils

openpnm/algorithms/GenericTransport.py, openpnm/core/Base.py, openpnm/core/Project.py, openpnm/network/CubicTemplate.py, openpnm/network/GenericNetwork.py, openpnm/topotools/topotools.py, tests/unit/core/BaseTest.py, tests/unit/core/ProjectTest.py
Trying to fix many of the little issues and bugs leading up to V2 release
=> Working on issues

openpnm/core/Base.py, tests/unit/core/BaseTest.py
small bug fix in clear method when models return dicts (so the dictionary name in the object doesn't match the model name in the models dictionary)
=> Fixing clear method for model_data, plus adding tests

openpnm/algorithms/GenericAlgorithm.py
Basic PR to add not implemented version of results, reset and update to the GenericAlgorithm class
=> adding empty methods to GenericAlgorithm

setup.py
Adding missing modules to setup.py
=> fixing setup.py to include all modules

openpnm/algorithms/FickianDiffusion.py, openpnm/algorithms/GenericAlgorithm.py, openpnm/algorithms/Porosimetry.py
Placing information in the settings of each class about if and how it should appear in the gui
=> Gui in settings

openpnm/algorithms/GenericTransport.py, openpnm/network/Bravais.py
Fixed labeling of Bravais face pores
=> Fix 1019 coplanar domain

openpnm/models/geometry/pore_size.py, openpnm/models/geometry/throat_size.py, openpnm/models/misc/__init__.py, openpnm/models/misc/misc.py, readme.md, tests/unit/models/geometry/PoreSizeTest.py, tests/unit/models/geometry/ThroatSIzeTest.py, tests/unit/models/misc/MiscTest.py
A new model that let's users specify an arbitrary numpy function as a model.  This let's custom calculations be intcorporated into the model regeneration pipeline.
=> Adding nump func model

openpnm/core/Subdomain.py, openpnm/models/misc/misc.py, openpnm/utils/Project.py, tests/unit/core/ProjectTest.py, tests/unit/models/misc/MiscTest.py
=> Fix from_neighbor_pore and from_neighbor_throat misc models

openpnm/io/GenericIO.py, openpnm/io/XDMF.py
Was writing abspath to the hdf5 file
=> Fixing major bug in xdmf file

openpnm/network/Cubic.py, openpnm/network/CubicTemplate.py
Address issue #1147 where the spacing argument was not being handled properly.
=> Fix missing spacing argument in CubicTemplate

openpnm/models/physics/diffusive_conductance.py, openpnm/models/physics/misc.py, tests/unit/models/physics/DiffusiveConductanceTest.py
Taylor-Aris model for advection-diffusion problems with a unit test.
=> Taylor-Aris model with test

example_transient_Fickian_diffusion.py, openpnm/io/CSV.py, openpnm/io/HDF5.py, openpnm/io/MAT.py, openpnm/io/VTK.py, openpnm/io/XDMF.py, openpnm/utils/Project.py, tests/unit/io/XDMFTest.py, tests/unit/utils/ProjectTest.py
Exception when trying to export transient data using a format other than "xdmf".
=> Export time series

tests/unit/models/physics/HydraulicConductanceTest.py
Removing bug from valvatne_blunt model test.
=> removing bug from test valvatne model. 

openpnm/algorithms/GenericTransport.py, openpnm/network/Cubic.py, openpnm/topotools/topotools.py, tests/unit/network/CubicTest.py
Addresses issues #1256 ,#1257.
=> Fix bug in _get_shape, which happens with small spacing values (<1e-9)

openpnm/physics/GenericPhysics.py, tests/unit/physics/GenericPhysicsTest.py
Adding a ``set_phase`` and ``set_geometry`` to the GenericPhysics class, and allowing empty geometry and phase arguments upon instantiation.
=> Enhance generic physics

openpnm/utils/Project.py, setup.py, tests/unit/utils/ProjectTest.py
Making the printing of grids simpler using terminaltable and pandas
=> Improve grid

openpnm/core/Base.py, tests/unit/core/BaseTest.py
=> Added set_label method to simplify manipulation of labels

openpnm/core/ModelsMixin.py, openpnm/io/CSV.py, openpnm/io/HDF5.py, openpnm/io/NetworkX.py, openpnm/io/Pandas.py, openpnm/io/Statoil.py, openpnm/models/physics/generic_source_term.py, openpnm/models/physics/meniscus.py, openpnm/topotools/topotools.py, tests/unit/io/NetworkXTest.py, tests/unit/models/physics/GenericSourceTermTest.py
Only import functions that are needed, instead of entire packages (specifically sympy, networkx and hdf5)....seems faster
=> Adjusting external package imports to improve speed of import openpnm

openpnm/utils/Project.py, tests/unit/utils/ProjectTest.py
The ``purge_object`` method on the ``Project`` now accepts a list of things to purge
=> Enhanced purge_object to accept list of objects

openpnm/algorithms/ReactiveTransport.py, tests/unit/algorithms/ReactiveTransportTest.py
=> Fix set_source bug where calling set_source w/ same propname led to duplicate source terms

openpnm/algorithms/TransientReactiveTransport.py, scripts/example_transient_AD.py, tests/unit/algorithms/TransientReactiveTransportTest.py
- Fixed issue #1357
- Updated transient advection diffusion example script, adding a reaction
=> Fix Transient with Crank Nicolson

openpnm/algorithms/GenericTransport.py, openpnm/models/geometry/throat_endpoints.py, openpnm/models/geometry/throat_length.py, openpnm/models/physics/hydraulic_conductance.py, tests/unit/core/ModelsTest.py, tests/unit/models/geometry/ThroatEndpointsTest.py, tests/unit/models/geometry/ThroatLengthTest.py
=> Hotfix: spherical_pores flow shape factor model ignored throat.centroid
