PMEAL/OpenPNM

OpenPNM/Algorithms/__GenericLinearTransport__.py
OpenPNM/Physics/models/generic_source_term.py
tests/test_source1.py
tests/test_source2.py
tests/test_source3.py
tests/test_source4.py
tests/test_source5.py

- This includes the new changes for the arguments in generic_source_term model of physics.
- The source parameters like A1, A2, ... should be sent only as string inputs such as 'pore.item' instead of the actual numerical values. The method looks into the physics or phase dictionaries to find the property.
- For examples, refer to the source tests in the test folder.

Feature source updates

---

.travis.yml
OpenPNM/__init__.py
bin/build
bin/clean
bin/publish
bin/test
setup.py

This PR adds a series of scripts to aid in the development of OpenPNM. They are all located in the `bin/` directory and can be called via:
```
$ bin/<script_name>
```
There are four scripts currently:
* `bin/test` Runs the test suite, the arguments `pep8` and/or `cov` can be added in order to test pep8 and test coverage respectively.
* `bin/build`: Builds OpenPNM
* `bin/publish`: Published OpenPNM to Pypi (It will probably prompt you for you pypi user info).
* `bin/clean`: Removes all files that result from any sort of build or test command
`bin/publish` should only run when we are ready for a release.
Please review: @jgostick @RodericDay

Work flow scripts

---

.travis.yml
bin/test

So the travisCI script is now fixed and will fail when our tests do. Keep in mind this will make our branch red. There are quite a few failures that @jgostick introduced which should be easy enough to fix.

Modified test script

---

OpenPNM/Algorithms/__GenericLinearTransport__.py
OpenPNM/Physics/models/multiphase.py

This PR fixes a bug in the multiphase model, so the model can work with the cloned physics too. 
The other commit is for checking the phase and algorithm length in the solver. I did not add this check to the generic algorithm, because we don't want to limit the user's ability for making new customized algorithms. But as for generic linear transport class, the length of phase and algorithm should always match together.

Bugfix multiphase

---

OpenPNM/Physics/models/multiphase.py
test/unit/Physics/models/MultiPhaseTest.py

It was the same problem with the conduit conductance model. It was written with the old OpenPNM style.
In the new form, everything must be calculated for the phase, but only values of the physics should be returned.

Fixed a bug in the late_pore_filling model

---

test/integration/test_topological_manipulations.py
test/unit/Base/ControllerTest.py

This PR corrects two tests that were testing OpenPNM's saving functionality outside of `TEMP_DIR`
cc/ @jgostick

Remove saving of vtp and net files

---

OpenPNM/Algorithms/__GenericLinearTransport__.py

If the solver (not the algorithm object) was in a loop, it was using an
attribute from the first iteration and consequently the result would be
the same each time. Now it is fixed.

Fixed minor bug in the solver

---

OpenPNM/Physics/__GenericPhysics__.py
test/unit/Physics/GenericPhysicsTest.py

This PR fixes issue #460 
When create a Physics object without sending a phase, the code used to create and EMPTY generic phase.  Now it creates a generic phase that is the associated with the network.

Fix bug460

---

OpenPNM/Base/__Core__.py
test/unit/Base/CoreTest.py
test/unit/Geometry/GenericGeometryTest.py
test/unit/Physics/GenericPhysicsTest.py

The PR address issue #468.  The point is to add some functionality and control to the Core clear method.  As it is now, it's a hammer that breaks everything.  This PR adds a 'modes' argument that lets the user clear the thing(s) they actually want.  The default behavior is still the same so it should remain backwards compatible.

Better clear

---

OpenPNM/Algorithms/__GenericLinearTransport__.py

It does not add any features to the code, but it prevents the code from producing the  unnecessary warning of root._parse_labels.

removed try_except from some sections of the code.

---

OpenPNM/Network/__Cubic__.py
test/unit/Network/CubicTest.py

Throat connections to the boundary pores were being added twice, AND there were no tests for this!  Both fixed.

fix_add_boundary_pores

---

OpenPNM/Network/__GenericNetwork__.py
test/unit/Network/GenericNetworkTest.py

Fixed issue #555.  It was finding correct throats, but apparently not all of them.  This fix works, but may not be fast as it converts to sets inside a for loop.  Optimize later if needed.

Changed the way duplicate throats are found.  

---

OpenPNM/Algorithms/__GenericAlgorithm__.py
OpenPNM/Algorithms/__GenericLinearTransport__.py
OpenPNM/Base/__Controller__.py
OpenPNM/Base/__Core__.py
OpenPNM/Base/__Tools__.py
OpenPNM/Geometry/__GenericGeometry__.py
OpenPNM/Network/__GenericNetwork__.py
OpenPNM/Phases/__GenericPhase__.py
OpenPNM/Physics/__GenericPhysics__.py
test/unit/Base/CoreTest.py
test/unit/Geometry/GenericGeometryTest.py

At present, related objects are stored on each other via hidden attribute (i.e. ```_geometries```).  These are accessed using a method ```geometries()``` which returns a list of object names.  This list is useless, and there are MANY places in the code where we iterate over the hidden list of actual objects.  SO, it seems that what we really want is for ```geometries``` to be an actual iterable.  I have used some really cool Python to:
(a) create a dict that stores our objects in the expected location (```geometries```) that we can now iterate over
(b) this dict has an added ```__call__``` method so that ```geometries()``` returns the expected list of strings AND ```geometries('some_name')``` returns the actual handle to the object.  The maintains backward compatibility
(c) the hidden …

Improved object lookup 2

---

OpenPNM/Network/__GenericNetwork__.py
test/unit/Network/GenericNetworkTest.py

The PR adds two features to ```num_neighbors```.  The ability to specify the 'mode' of the count, and the ability to count neighbor pores and throats. In the backend this also abstracts ```find_neighbor_pores``` and ```find_neighbor_throats``` into a single private method ```_find_neighbors``` that both call.

Add element to num neighbors

---

OpenPNM/Physics/models/hydraulic_conductance.py
OpenPNM/Utilities/misc.py
run_script.py
test/unit/Physics/GenericPhysicsTest.py
test/unit/Physics/models/DiffusiveConductanceTest.py
test/unit/Physics/models/HydraulicConductance.py

There is a bug in the Utilities.misc.conduit_length code that calculates longer lengths when boundary pores are present...this PR comments out 2 lines that fix the problem, but we need to come up with a complete solution...
Also, should this conduit length calculator be a pore-scale model?

Fix issue 566

---

OpenPNM/Base/__Core__.py
OpenPNM/Network/__GenericNetwork__.py
OpenPNM/Phases/__GenericPhase__.py

This PR fixes issue #579 pertaining to the mode deep in the ```props``` method.  I've actually changed the code a bit so that deep is now an argument not a mode, but have tried to maintain backwards compatibility.

Fix 579 using deep mode

---

OpenPNM/Network/tools.py

There was a dummy network in the subdivided method, which would appear
in the workspace. Now the object will be purged after running the
method. This PR addresses the issue  #587.

removed_dummy_subdivided_network

---

.travis.yml

Seeing what happens when atlas and fortran compilers are not installed...anaconda should be coming with a binary of numpy so these aren't needed.

Fixing TravisCI Python3.3 build error

---

OpenPNM/Network/tools.py

Added a function to Network.tools that finds pores on the surface of any network and labels them as 'pore.surface', to address issue #527.  This method uses a watershed transport to segment the space around each pore center, then labels all pores whose watershed basin touches the edge of the image as a surface pore.  Because it uses image analysis tricks, it can be slow in some cases: particularly subdivided networks.

Find surface pores

---

.travis.yml
OpenPNM/Base/__Core__.py
OpenPNM/Base/__Tools__.py
test/unit/Base/CoreTest.py
test/unit/Base/ToolsTest.py

Adjusted the __str__ function on Core to not show any dict keys starting with 'pore._' or throat._'.  Also adjust the PrintableList to do the same.  This way print(pn), print(pn.props()), and print(pn.labels()) will all exclude the hidden or private arrays.
Actually implementing this throughout the code will be a pain, but at least the framework is ready.

Allowing for hidden or private dictionary entries

---

OpenPNM/Phases/__Water__.py
OpenPNM/Phases/models/vapor_pressure.py
test/unit/Phases/models/VaporPressureTest.py

This PR addresses the issue #609 and fixes a bug in the Antoine parameters for water. We had the correct values before, but apparently they had been changed in the recent versions. Now, it is fixed.

Antoine parameters

---

OpenPNM/Network/__CubicDual__.py
OpenPNM/Network/__init__.py
test/unit/Network/CubicDualTest.py

This PR adds a CubicDual class to the suite of Network generators.  This class creates a standard cubic, but with an another cubic network interpenetrating it offset by half a lattice cell.  These two dual networks are also connected to each other, which allows exchange of material between them such as heat transfer, or perhaps to model mass transfer from pores centers to walls.  This class is added as the cubic counter part to the DelaunayVoronoiDual class added in PR #604 .

Dual cubic

---

OpenPNM/Utilities/IO.py

as discussed in #628 the following changes were made:
1. replace '\t' and '\n' in row string by ' ', and then split - will consider subsequent whitespace as just one whitespace
replace('\t',' ').replace('\n',' ').split()
2. clean up those parts of the code that did manual splitting for just one whitespace using spit(' ') by just using split without argument as split()

Bugfix for #628 Utilities.IO.Statoil breaking for large networks

---

OpenPNM/Network/tools.py
test/integration/test_topological_manipulations.py

This PR addresses the issue  #617 and is just a quick fix for the problem that some users might have had. Before, it was allowing user to run the subdivide method consecutively, but right now, it raises an Exception. Because creating the proper connections is really complicated when it comes to the different spacing and scales.

Debugged subdivide method

---

OpenPNM/Network/tools.py
test/integration/script_test.py
test/unit/Utilities/TopologyTest.py

This PR addresses the issue  #624. Another wrapper method has been added for making circular templates. So "template_sphere_shell" and "template_circle_ring" call one private method in the network 'tools' that produces the image arrays. This PR is compatible with the previous codes. Also unit tests have been added for the new method.

Added a method for circular templates

---

OpenPNM/Network/__CubicDual__.py
OpenPNM/Network/tools.py
test/unit/Network/CubicDualTest.py

There was a major bug in this class (the network size was being hard coded, presumably due to some left over debugging lines).  This could have been avoided it we'd done proper team-based code review before merging.  Also, I took the opportunity to adjust how the duals were generated, so now requesting a shape of [4,4,4] returns a [4,4,4].  It was previously being padded to [5,5,5], which was not very logical.

Fix cubic dual

---

OpenPNM/Algorithms/__GenericLinearTransport__.py

There was a minor typo in one of the warnings for the labels of BC method.
Now, it is fixed.

Fixed a typo

---

OpenPNM/Algorithms/__GenericLinearTransport__.py
test/integration/script_test.py

There was a bug in the 'single' mode of the 'rate' function. Apparently, at some point, 'len' has been replaced by 'size'. I changed it to 'shape'.

Fixed a bug in (rate) function

---

OpenPNM/Base/__Core__.py

Fixing the error in the pores and throats methods that used a shortcut when label was 'all'

Fix Issue #672

---

OpenPNM/Utilities/IO.py
test/unit/Utilities/IOTest.py

As per personal communication with @jgostick , `NetworkX.load()` is replaced by a function that accepts a `networkX` graph directly, instead of using an intermediate YAML file.
Checks on the input graph:
- Checking if supplied object is networkX graph
- Checking if supplied graph is undirected
- Checking if numbering of G.nodes() contains any gaps
- Checking if numbering of G.nodes() starts at 0
The implementation is very similar to the original YAML approach. There was no need to remove duplicates from `conns` anymore, but it's still sorting because I could not determine if `G.edges()` returns a sorted list.
I didn't manage to fill an `ndarray` of strings, such as `_sp.ndarray((N,M), dtype=str)`, correctly. hence there are a few checks to see if `dtype` is `str`. Without these checks and …

Read networkx graph object directly

---

openpnm/core/Base.py
openpnm/network/GenericNetwork.py
openpnm/phases/GenericPhase.py

Making interleave data a public method and removing the sources argument, which it can find itself now.

making interleave data public

---

openpnm/core/ModelsMixin.py
requirements.txt
test_requirements.txt
tests/unit/core/ModelsTest.py

fixes a minor issue, making it easier to see which dependencies have not been run.  It does NOT show the entire tree of missing deps, only those missing for the current model being regenerated.  Still better than before.

Missing dep message

---

openpnm/models/geometry/throat_equivalent_area.py
openpnm/models/geometry/throat_length.py
openpnm/models/physics/hydraulic_conductance.py
openpnm/models/physics/misc.py

There are two critical bugs in these models:
1. `map_throats` is incorrectly being called on `geometry`, rather than `network`.
2. Filtered data from geometry (for instance `dt = target['throat.diameter']` were being re-filtered by an incorrect map from map_throats (for instance `dt = target['throat.diameter'][throats]` where `throats = target.map_throats(target['throat._id'])`).

Critical bug in conduit_lengths and equivalent_area models

---

example_script.py
openpnm/core/Base.py
openpnm/models/geometry/throat_equivalent_area.py
openpnm/models/geometry/throat_length.py
openpnm/models/physics/hydraulic_conductance.py
openpnm/models/physics/misc.py
openpnm/models/physics/multiphase.py
openpnm/topotools/topotools.py
openpnm/utils/Project.py
openpnm/utils/vertexops.py
tests/unit/core/BaseTest.py

The mapping functions used to take IDs as arguments, now they take pore numbers and the associated object.  It hides ids from the users.

Changing the API for the mapping functions

---

openpnm/algorithms/GenericTransport.py
openpnm/algorithms/ReactiveTransport.py
requirements.txt
setup.py
tests/unit/algorithms/GenericTransportTest.py

This was added to force scipy to use the 64 bit version of umfpack and hence increase the allowed memory.  It works!

Minor tweak to use 64 bit integers in A matrix

---

openpnm/io/VTK.py

A very basic fix to this.  It's odd that it broke though.  It was checking to makes sure `element` existed before attempting to write it, but this object no longer evaluates to true.  I just removed the check.

fixing_broken_VTK

---

openpnm/core/Base.py

Previously, `_map` used a list comprehension to generate a hash_map. I modified it, so it uses numpy arrays. Now, `_map` is about 3X faster.

Optimize _map method

---

openpnm/models/geometry/throat_length.py

This is useful when dealing with undefined geometries. Previously, since numpy's norm was used to calculate the distance between points, models wouldn't run complaining there's nans in pore.diameter/etc. Now, distance calculation is done manually, and annoying numpy RuntimeWarnings are caught on the fly.

Improve nans support in throat_length models

---

openpnm/core/Base.py
tests/unit/core/BaseTest.py

Subclasses the ``get`` method to return a partial dict of just the specified properties if a list of strings is given, otherwise calls the super methods and behaves as normal. There are two reasons for doing this: (1) The get method is already there so might as well turn it into something useful, and (2) it would be handy to extract all 'pore' information (for example) and create a pandas data frame from it directly.  This can't be done if throat info is mixed in since the column lenghts don't match.

Subclass get

---

openpnm/topotools/topotools.py
setup.cfg
tests/unit/topotools/TopotoolsTest.py

If you want to consecutively merge selections of pores, you need to consecutively call merge_pores (obviously) but since at the end of each call, the adjacency matrix is rebuilt, it's super slow. This PR basically enables merge_pores to accept list of lists of pores (instead of single list of pores), so the rebuilding of the adjacency matrix only happens once. This small change significantly speeds up the whole process of consecutively merging pores. (related to issue #1104)

Improve merge_pores to be able to merge list of lists of pores

---

openpnm/algorithms/AdvectionDiffusion.py
tests/unit/algorithms/AdvectionDiffusionTest.py

Addressing issue #1150. This PR adds an exclusive rate method for AdvectionDiffusion algorithm. This method overrides the rate method on GenericTransport since it only accounted for diffusive flux.

Exclusive rate method for AdvectionDiffusion algorithm

---

openpnm/materials/VoronoiFibers.py

Catch the voxels that escape the hull image procedure and assign them to the nearest pore (using max_filter). Scikit-image flood fill would potentially be faster but is not implemented yet and speed is not so bad

Fix Voronoi Hulls

---

openpnm/topotools/topotools.py
tests/unit/topotools/TopotoolsTest.py

This PR addresses issue #693. The coordinates of the new pore after merging some pores used to be computed by averaging the coordinates of the input pores. This method was problematic when input pores were not uniformly distributed (ex. subdividing a pore leads to a high pore density in a small area, so if the subdivided pores were to be merged along with a bunch of neighboring pores, the coordinates of the new pore after merging would be skewed towards the subdivided region).

Fix coords of merged pores

---

openpnm/network/Cubic.py

This PR optimizes Cubic network generation speed. The optimization was done by replacing the list comprehension for generating pore coordinates by a numpy-vectorized version. This small modification makes Cubic network generation about 2.5x faster. Here's a speed comparison between the two branches (`dev` and `optimize_Cubic`) for different network sizes ranging from 10 thousand to 10 million pores.

Optimize Cubic network generation speed

---

.gitignore
openpnm/network/Cubic.py

This PR further optimizes Cubic network generation by vectorizing the part of the code that is responsible for making connections between pores. Here's a speed comparison between master, dev (only the part for node generation was optimized), and this branch.

Further optimize Cubic network generation

---

example_PNP.py
openpnm/topotools/topotools.py

This PR addresses issues #1126 and #623. The scaling problem in 2D for `plot_connections` is now fixed. Also, if 1/2D networks are passed, no longer the plot is 3D. I also refactored `plot_coordinates` and `plot_connections` a little bit.

Refactor plot_conns and plot_coords, fix scaling issue plot_conns in 2D

---

example_transient_Fickian_diffusion.py
openpnm/io/GenericIO.py
openpnm/io/VTK.py
openpnm/io/XDMF.py
openpnm/utils/Project.py
tests/unit/io/XDMFTest.py
tests/unit/utils/ProjectTest.py

Export transient data in XDMF format.
1- Supports transient and steady-state data
2- Steady-state data (such as geometrical properties) are not duplicated over transient files.
3- On Paraview, the Steady-state data are present at all time steps by pointing the "xmf" file to the initial time step file "hdf" which contains all the steady-state data.
4- Removed the option to export VTK files with time series as it doesn't properly handle non-uniform time steps AND generate large files...
5- When times series are present in phases, proj.export_data method will ALWAYS export in XDMF format an print a warning if the user requested to export into another format.

Support for transient data

---

example_ad_02.py
openpnm/algorithms/AdvectionDiffusion.py
openpnm/algorithms/Dispersion.py
openpnm/algorithms/TransientAdvectionDiffusion.py
openpnm/algorithms/TransientReactiveTransport.py
openpnm/models/physics/__init__.py
openpnm/models/physics/ad_dif_conductance.py
openpnm/models/physics/ad_dif_mig_conductance.py
openpnm/models/physics/dispersive_conductance.py
tests/unit/algorithms/AdvectionDiffusionTest.py
tests/unit/algorithms/TransientAdvectionDiffusionTest.py

Related to issue #1253.
1/ Kept both **AdvectionDiffusion** and **Dispersion** algorithms (the former inherits from the latter)
2/ Added a new **ad_dif_conductance** model for the **AdvectionDiffusion** algorithm (which inherits from the **dispersive_conductance**) and deleted the **_build_A** from the **AdvectionDiffusion** algorithm
3/ Fixed tests
4/ Improved the **alg.results** method in **TransientReactiveTransport**
5/ Other changes to make sure the **outflow_BC** and **rate** methods work correctly

remove build_A from AD alg, add cd model, fix tests, improve alg.results

---

openpnm/topotools/topotools.py
setup.py

We only use porespy once in topotools where make_contigueous is called. make_contigueous is now replaced w/ scipy's rankdata so porespy can be safely removed from OpenPNM dependencies, ultimately fixing our circular dependency issue.

Remove porespy from OpenPNM dependencies

---

.gitignore
setup.cfg
setup.py

This pull request adds the LICENSE file to source and binary distributions, adds some additional metadata to the `setup()` call, and ignores the temporary files from a build.

Add license_file metadata and other metadata

---

.travis.yml
openpnm/algorithms/OrdinaryPercolation.py
tests/unit/algorithms/PorosimetryTest.py

The inlet pores were set to filled at start of OrdinaryPercolation, which caused significant confusion.  I have changed this so that inlet pores are only filled once the largest throat leading from the pore is invaded.  The reason it was not done like this before, was that this behavior is a bit arbitrary.  This change will make things much less confusing, so it's worth it.

Changing behavior of inlet filling in OrdinaryPercolation

---

openpnm/core/Base.py
tests/unit/core/BaseTest.py

The standard ``pores`` and ``throats`` methods now have a ``target`` argument that means you can use ``pn.pores('left', target=get)`` to get the indices of the 'left' pores on the ``geo`` object.  Backwards compatible and default behavior is same as before.

Add target to pores and throats

---

openpnm/models/geometry/throat_volume.py
tests/unit/models/geometry/ThroatVolumeTest.py

This PR adds two simple models for calculating the volume of lens and pendular rings due to overlap or not of cylindrical throats and spherical pores.  The lens model is meant to be subtracted from the throat volume in the overlapping case (when throat.endpoints are used) and the pendular_rings model is meant to be added in the case when sphere and throats just barely contact each other.

Lens volume models

---

openpnm/algorithms/GenericTransport.py
openpnm/algorithms/ReactiveTransport.py
tests/unit/algorithms/GenericTransportTest.py
tests/unit/algorithms/ReactiveTransportTest.py

This should enable the re-use of algorithm objects inside for loops

Adding reset method to GenericTransport and ReactiveTransport

---

openpnm/algorithms/GenericTransport.py
openpnm/algorithms/InvasionPercolation.py
openpnm/algorithms/MixedInvasionPercolation.py
openpnm/algorithms/OrdinaryPercolation.py
openpnm/algorithms/metrics/RelativePermeability.py
openpnm/core/Base.py
openpnm/core/ModelsMixin.py
openpnm/io/CSV.py
openpnm/io/JSONGraphFormat.py
openpnm/io/NetworkX.py
openpnm/io/Pandas.py
openpnm/io/Statoil.py
openpnm/materials/BundleOfTubes.py
openpnm/materials/VoronoiFibers.py
openpnm/models/misc/statistical_distributions.py
openpnm/models/phases/partition_coefficient.py
openpnm/models/physics/generic_source_term.py
openpnm/models/physics/meniscus.py
openpnm/network/DelaunayVoronoiDual.py
openpnm/network/GenericNetwork.py
openpnm/topotools/topotools.py
openpnm/utils/Project.py
tests/unit/core/BaseTest.py
tests/unit/core/UnytTest.py

This PR fixes #1113. The main culprit libraries turned out to be `unyt` and `sympy`. They are now imported internally in methods, rather than in the file header.
I also made some other `import` optimizations for packages that are only occasionally used. The average `OpenPNM` import time is now down to about **0.3** seconds from about **2.1** seconds (on my workstation).
For future reference, [`tuna`](https://github.com/nschloe/tuna) helped a lot in tracking down the problematic libraries.

Optimize OpenPNM import time

---

setup.py

This PR fixes #1352. Basically, the problem was that the old PyPI could only render `rst` files, but the new one (since late 2018) is much more advanced and can even render GitHub-flavored `markdown`. You only need to explicitly state that in `setup.py`.
Ref: https://packaging.python.org/guides/making-a-pypi-friendly-readme/

Fix PyPI issue with our README.md

---

example.py
openpnm/models/physics/generic_source_term.py
tests/unit/algorithms/ReactiveTransportTest.py
tests/unit/algorithms/TransientReactiveTransportTest.py
tests/unit/models/physics/GenericSourceTermTest.py

This PR fixes #1366. Basically, our previous default values for some of the pore-scale models led to non-zero rates, which was confusing for some users (for instance, when using `linear`, a user assumed `A1` is by default zero and only set `A2`, which led to a hard-to-debug situation).
Also, for consistency, `quantity` argument was renamed to `X` in `standard_kinetics` like the rest of the source term models (fixes #1386)

Default values for source term pore-scale models must ensure zero rate/S1/S2

---

openpnm/models/misc/neighbor_lookups.py
tests/integration/MultidomainTest.py

The from_neighbor_pores model was breaking on domains that had no throats...now fixed.

Fix1408 throat models break with no throats

---

openpnm/topotools/topotools.py
tests/unit/topotools/TopotoolsTest.py

This PR fixes issue #1388. `plot_networkx` now supports 1D networks, and is also much more robust with respect to inferring pore size/doing the right thing if not found.

Enhance plot_networkx

---

openpnm/network/CubicTemplate.py
openpnm/network/GenericNetwork.py
tests/unit/network/CubicTemplateTest.py

This PR fixes issue #1427, addressing the slow instantiation of `CubicTemplate` due to the call to `find_surface_pores` method. It doesn't do that anymore, `"pore.internal_surface"` label was introduced, which indicates surface pores that are not part of the "exterior" of the network.

Enhance CubicTemplate
